[1404-lubuntu-dev-vbox-vagrant]
distro = "ubuntu"
description = "ubuntu LTS 1404 amd64 lubuntu build w some languages and editors"
arch = "amd64"
image = "server"
release = "14.04"
builder_types = [
	"virtualbox-iso"
]
	[1404-lubuntu-dev-vbox-vagrant.builders]
		[1404-lubuntu-dev-vbox-vagrant.builders.virtualbox-iso.arrays]
		vboxmanage = [
			"cpus=1",
			"memory=2048",
			"vram=128",
			"accelerate3d=on",
			"clipboard=bidirectional"
		]
	[1404-lubuntu-dev-vbox-vagrant.provisioners]
		[1404-lubuntu-dev-vbox-vagrant.provisioners.shell]
			[1404-lubuntu-dev-vbox-vagrant.provisioners.shell.arrays]
			scripts = [ 
				"setup",
				"sudoers",
				"user_vagrant",
				"desktop",
				"browsers",
				"editors",
				"dev",
				"go",
				"timezone",
				"vbox",
				"cleanup"
			]

[1504-lubuntu-dev-vbox-vagrant]
distro = "ubuntu"
description = "ubuntu LTS 1504 amd64 lubuntu build w some languages and editors"
arch = "amd64"
image = "server"
release = "15.04"
builder_types = [
	"virtualbox-iso"
]
	[1504-lubuntu-dev-vbox-vagrant.builders]
		[1504-lubuntu-dev-vbox-vagrant.builders.virtualbox-iso.arrays]
		vboxmanage = [
			"cpus=1",
			"memory=2048",
			"vram=128",
			"accelerate3d=on",
			"clipboard=bidirectional"
		]
	[1504-lubuntu-dev-vbox-vagrant.provisioners]
		[1504-lubuntu-dev-vbox-vagrant.provisioners.shell]
			[1504-lubuntu-dev-vbox-vagrant.provisioners.shell.arrays]
			scripts = [ 
				"setup",
				"sudoers",
				"user_vagrant",
				"desktop",
				"browsers",
				"editors",
				"dev",
				"go",
				"timezone",	
				"vbox",
				"cleanup"
			]

[jessie-lxde-go-vbox]
distro = "debian"
description = "minimal debian jessie amd64 virtualbox vagrant build"
arch = "amd64"
image = "netinst"
release = "8"
builder_types = [
	"virtualbox-iso"
]
# unset vagrant
post_processor_types = []
	[jessie-lxde-go-vbox.builders]
		[jessie-lxde-go-vbox.builders.virtualbox-iso.arrays]
		vboxmanage = [
			"cpus=1",
			"memory=2048",
			"vram=128",
			"accelerate3d=on",
			"clipboard=bidirectional"
		]
	[jessie-lxde-go-vbox.provisioners]
		[jessie-lxde-go-vbox.provisioners.shell.arrays]
		scripts = [ 
			"setup",
			"sudoers",
			"user_vagrant",
			"timezone",
			"desktop",
			"browsers",
			"editors",
			"go",
			"vbox",
			"cleanup"
		]
