#!/bin/bash
# install a lightweight desktop
PATH=$PATH:/sbin:/usr/sbin:/usr/local/sbin
DEBIAN_FRONTEND=noninteractive apt-get update
DEBIAN_FRONTEND=noninteractive apt-get install -y xorg xserver-xorg
DEBIAN_FRONTEND=noninteractive apt-get install -y lxde
DEBIAN_FRONTEND=noninteractive apt-get install -y lightdm
# add irc client
DEBIAN_FRONTEND=noninteractive apt-get install -y quassel
# remove screensaver
DEBIAN_FRONTEND=noninteractive apt-get install -y apt-get remove xscreensaver
# install sound
DEBIAN_FRONTEND=noninteractive apt-get install -y alsa-utils
