#!/bin/bash
# editors
PATH=$PATH:/sbin:/usr/sbin:/usr/local/sbin
# install vim and emacs
apt-get install -y vim emacs

# alternate text editor
apt-get install -y gedit

# install current atom: https://atom.io
apt-get install 0-y gvfs-bin
curl -L https://atom.io/download/deb > atom-amd64.deb
dpkg --install atom-amd64.deb
#apt-get install -y -f
rm -f /home/vagrant/atom-amd64.deb

# vim.spf13.com
su - vagrant <<'EOF'
curl http://j.mp/spf13-vim3 -L -o - | sh
echo "let g:spf13_bundle_groups=['general', 'neocomplete', 'programming', 'ruby', 'python', 'go', 'javascript', 'html', 'misc', 'writing' ]" >> ~/.vimrc.before.local 
vim +BundleInstall! +qall
:GoInstallBinaries
EOF
