#!/usr/bin/env bash
PATH=$PATH:/sbin:/usr/sbin:/usr/local/sbin
DEBIAN_FRONTEND=noninteractive apt-get update
wget -qO- https://storage.googleapis.com/golang/go1.5.3.linux-amd64.tar.gz | sudo tar xz -C /usr/local

# liteide: latest
wget -qO- http://sourceforge.net/projects/liteide/files/latest/download?source=files | sudo tar -C /usr/local -xj

# Add some aliases for Go
ALIASES=/home/vagrant/.bash_aliases
echo "" >> $ALIASES
echo "# Some Go aliases" >> $ALIASES
echo "alias s='cd ~/go/src/'" >> $ALIASES
echo "alias g='cd ~/go/src/github.com/'" >> $ALIASES

# Go should be installed under the user not root
su - vagrant <<'EOF'
export GOPATH=$HOME/go
export PATH=$PATH:/usr/local/go/bin:$HOME/go/bin:/usr/local/liteide/bin
echo 'export GOPATH=$HOME/go' >> ~vagrant/.bashrc
echo 'export PATH=$PATH:/usr/local/go/bin:$HOME/go/bin:/usr/local/liteide/bin' >> ~vagrant/.bashrc
source ~vagrant/.bashrc

# make the GOPATH dir
mkdir ~vagrant/go

# delve debugger: https://github.com/derekparker/delve
go get github.com/derekparker/delve/cmd/dlv

EOF
