#!/bin/bash
# install browsers and stuff
# quassel for irc: hnot a browser, but here it is.
DEBIAN_FRONTEND=noninteractive apt-get install -y quassel

# chrome
PATH=$PATH:/sbin:/usr/sbin:/usr/local/sbin
wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
dpkg -i google-chrome-stable_current_amd64.deb
DEBIAN_FRONTEND=noninteractive apt-get install -y -f

# chromium
DEBIAN_FRONTEND=noninteractive apt-get update
DEBIAN_FRONTEND=noninteractive apt-get install -y chromium-browser
