#!/bin/bash
# editors
# set path as sudo is inheriting environment, which doesn't include sbin stuff
# this could probably be resolved through sudoers config
PATH=$PATH:/sbin:/usr/sbin:/usr/local/sbin
# install vim and emacs
DEBIAN_FRONTEND=noninteractive apt-get install -y vim emacs

# install atom: https://atom.io
# 1.0.5 is latest at time of script creation
wget https://github.com/atom/atom/releases/download/v1.0.5/atom-amd64.deb
dpkg --install atom-amd64.deb
DEBIAN_FRONTEND=noninteractive apt-get install -y -f
rm -f /home/vagrant/atom-amd64.deb
