#!/bin/bash
# install commonly used programs
# quassel for irc: not a browser, but here it is.
apt-get install -y quassel

# chrome
wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
dpkg -i google-chrome-stable_current_amd64.deb
apt-get install -y -f
rm -f google-chrome-stable_current_amd64.deb

# chromium
apt-get update
apt-get install -y chromium-browser