#!/bin/bash
# editors
# set path as sudo is inheriting environment, which doesn't include sbin stuff
# this could probably be resolved through sudoers config
PATH=$PATH:/sbin:/usr/sbin:/usr/local/sbin
# install vim and emacs
apt-get install -y vim emacs

# alternate text editor
apt-get install -y gedit

# install current atom: https://atom.io
apt-get install 0-y gvfs-bin
curl -L https://atom.io/download/deb > atom-amd64.deb
dpkg --install atom-amd64.deb
#apt-get install -y -f
rm -f /home/vagrant/atom-amd64.deb

