#!/bin/bash

# Go should be installed under the user not root
su vagrant  <<'EOF'
echo export GOPATH=$HOME/code/go >> ~vagrant/.bashrc
echo export PATH=$PATH:/usr/local/go/bin:$HOME/code/go/bin >> ~vagrant/.bashrc
exec bash
wget -qO- https://storage.googleapis.com/golang/go1.5.3.linux-amd64.tar.gz | sudo tar xz -C /usr/local
mkdir ~vagrant/code
mkdir ~vagrant/code/go

# Add some aliases for Go
ALIASES = /home/vagrant/.bash_aliases
echo "" >> $ALIASES
echo "# Some Go aliases" >> $ALIASES
echo "alias s='cd ~/code/go/src/'" >> $ALIASES
echo "alias g='cd ~/code/go/github.com/'" >> $ALIASES

EOF
