#!/bin/bash

WORKSPACE=$HOME/code/go
# Go should be installed under the user not root
su - vagrant  <<'EOF'
cd /tmp
wget https://raw.githubusercontent.com/mohae/install-go/master/install_current
chmod +x install_current
./install_current -w $WORKSPACE

# Add some aliases for Go
ALIASES=$HOME/.bash_aliases
echo "" >> $ALIASES
echo "# Some Go aliases" >> $ALIASES
echo "alias s='cd ~/go/src/'" >> $ALIASES
echo "alias g='cd ~/go/src/github.com/'" >> $ALIASES
EOF
