#!/bin/bash

# Go should be installed under the user not root
su vagrant  <<'EOF'
echo export GOPATH=$HOME/code/go >> ~vagrant/.bashrc
echo export PATH=$PATH:/usr/local/go/bin:$HOME/code/go/bin >> ~vagrant/.bashrc
exec bash
wget -qO- https://storage.googleapis.com/golang/go1.5.3.linux-amd64.tar.gz | sudo tar xz -C /usr/local
mkdir ~vagrant/code
mkdir ~vagrant/code/go

EOF
