#!/bin/bash

# java
DEBIAN_FRONTEND=noninteractive apt-get install -y default-jre
DEBIAN_FRONTEND=noninteractive apt-get install -y default-jdk
wget http://ftp.osuosl.org/pub/eclipse/technology/epp/downloads/release/mars/2/eclipse-java-mars-2-linux-gtk-x86_64.tar.gz -O /tmp/eclipse.tar.gz && tar xzf /tmp/eclipse.tar.gz -C /usr/share
# Java workspace should be under user, not root
su vagrant  <<'EOF'
mkdir -p ~vagrant/code/java/workspace

EOF

# add the menu shortcut
cp /tmp/eclipse.desktop /usr/share/applications/eclipse.desktop
# update the default workspace
sed -i 's/osgi.instance.area.default=@user.home\/workspace/osgi.instance.area.default=@user.home\/code\/java\/workspace/' /usr/share/eclipse/configuration/config.ini  
