# Builds are named configurations that specify the distro to use, at minimum, and 
# define the final overrides and settings for generating a Packer Template. The 
# generated Packer template will be the result of merging the settings within the
# build configuration with the Rancher and distro defaults.

# These all target the "virtualbox-iso" builder only. For build templates that target
# multiple builders, the "override" setting needs to be supported. Until that occurs
# separate templates will be needed instead; e.g. instead of a build targeting both
# "virtualbox-iso" and "vmware-iso" using the "shell" provisioner, these will need to
# be separated to different build templates as the "virtualbox-iso" template would need
# the "vbox" shell script while the "vmware-iso" template would need the "vmware" shell
# script. 
#
# Support for override is coming, but may require a rework of the way Rancher build 
# templates are defined.
[1404-64-vbox-vagrant]
distro = "ubuntu"
description = "minimal ubuntu LTS 1404 amd64 virtualbox vagrant build"
arch = "amd64"
image = "server"
release = "14.04"
builder_types = [
	"virtualbox-iso"
]
	[1404-64-vbox-vagrant.provisioners.shell.arrays]
	scripts = [ 
		"setup",
		"sudoers",
		"user_vagrant",
		"vbox",
		"cleanup",
	]
[1504-64-vbox-vagrant]
distro = "ubuntu"
description = "minimal ubuntu LTS 1404 amd64 virtualbox vagrant build"
arch = "amd64"
image = "server"
release = "15.04"
builder_types = [
	"virtualbox-iso"
]
	[1504-64-vbox-vagrant.provisioners.shell.arrays]
	scripts = [ 
		"setup",
		"sudoers",
		"user_vagrant",
		"vbox",
		"cleanup",
	]	
[centos6-64-vbox-vagrant]
distro = "centos"
description = "minimal centos 6 x86_64 virtualbox vagrant build"
arch = "x86_64"
image = "Minimal"
release = "6"
builder_types = [
	"virtualbox-iso"
]
	[centos6-64-vbox-vagrant.provisioners.shell.arrays]
	scripts = [ 
		"setup",
		"sudoers",
		"user_vagrant",
		"vbox",			
		"cleanup"
	]

[centos7-64-vbox-vagrant]
distro = "centos"
description = "minimal centos 7 x86_64 virtualbox vagrant build"
arch = "x86_64"
image = "Minimal"
release = "7"
builder_types = [
	"virtualbox-iso"
]
	[centos7-64-vbox-vagrant.provisioners.shell.arrays]
	scripts = [ 
		"setup",
		"sudoers",
		"user_vagrant",
		"vbox",
		"cleanup"
	]
			
[jessie-64-vbox-vagrant]
distro = "debian"
description = "minimal debian jessie amd64 virtualbox vagrant build"
arch = "amd64"
image = "netinst"
release = "8"
builder_types = [
	"virtualbox-iso"
]
	[jessie-64-vbox-vagrant.provisioners.shell.arrays]
	scripts = [ 
		"setup",
		"sudoers",
		"user_vagrant",
		"vbox",
		"cleanup"
	]