# Default settings for Rancher templates.  Merging the contents of this file
# with the supported config file settings results in the default template for
# Rancher. 
#
description = "Default Rancher template"
name = ":build_name"
output_dir = "../packer_templates/:build_name"
source_dir = "packer_sources"
include_component_string = "true"
min_packer_version = "0.7.0"
builder_types = [
	"virtualbox-iso",
	"vmware-iso",
]
post_processor_types = [
	"vagrant"
]
provisioner_types = [
	"shell"
]
[builders]
	[builders.common]
		settings = [	
			"boot_command = boot.command",
			"boot_wait = 5s",
			"disk_size = 40000",
			"guest_os_type=",
			"headless = true",
			"http_directory = http",
			"iso_checksum_type = sha256",
			"output_directory = :output_dir",
			"shutdown_command = shutdown.command",
			"ssh_password = vagrant",
			"ssh_port = 22",
			"ssh_username = vagrant",
			"ssh_wait_timeout = 5m",
			"vm_name = :build_name",
		]
	[builders.virtualbox-iso]
		settings = [
			"guest_additions_path = VBoxGuestAdditions_{{ .Version }}.iso",
			"virtualbox_version_file = .vbox_version"
		]
		[builders.virtualbox-iso.arrays]
			vboxmanage = [
				"cpus=1",
				"memory=1024"	
			]
	[builders.vmware-iso]
		[builders.vmware-iso.arrays]
			vmx_data = [
				"cpuid.coresPerSocker=1",
				"numvcpus=1",
				"memsize=1024"
			]
[post_processors]
	[post_processors.vagrant]
		settings = [
			"compression_level = 9",
			"keep_input_artifact = false",
			"output =  :build_name.box"
		]
[provisioners]
	[provisioners.shell]
		settings = [
			"execute_command = execute.command"
		]
		[provisioners.shell.arrays]
			scripts = [ 
				"setup.sh",
				"sudoers.sh",
				"vagrant.sh",
				"cleanup.sh",
			]
