[1404-dev]
	distro = "ubuntu"
	description = "ubuntu LTS 1404 amd64 vagrant build"
	arch = "amd64"
	image = "server"
	release = "14.04"
	builder_types = [
		"virtualbox-iso"
	]
	[1404-dev.builders]
		[1404-dev.builders.common]
			settings = [
				"ssh_wait_timeout = 30m"
			]
	[1404-dev.provisioners]
		[1404-dev.provisioners.shell]
			[1404-dev.provisioners.shell.arrays]
				scripts = [ 
					"vagrant.sh",
					"sudoers.sh",
					"setup.sh",
					"desktop.sh",
					"browsers.sh",
					"editors.sh",
					"dev.sh",
					"go.sh",
					"cleanup.sh",
				]
[jessie-go]
	distro = "debian"
	description = "debian jessie amd64 vagrant build"
	arch = "amd64"
	image = "netinst"
	release = "8"
	builder_types = [
		"virtualbox-iso"
	]
	[jessie-go.builders]
		[jessie-go.builders.common]
			settings = [
				"ssh_wait_timeout = 30m"
			]
	[jessie-go.provisioners]
		[jessie-go.provisioners.shell]
			[jessie-go.provisioners.shell.arrays]
				scripts = [ 
					"vagrant.sh",
					"setup.sh",
					"browsers.sh",
					"editors.sh",
					"go.sh",
					"cleanup.sh",
				]

