[jessie-salty-vbox-vagrant]
distro = "debian"
description = "debian jessie amd64 virtualbox vagrant build w salt installed"
arch = "amd64"
image = "netinst"
release = "8"
builder_types = [
	"virtualbox-iso"
]
	[jessie-salty-vbox-vagrant.provisioners.shell.arrays]
	scripts = [
		"setup",
		"sudoers",
		"user_vagrant",
		"salt",
		"vbox",
		"cleanup"
	]
#
[1404-salty-vbox-vagrant]
distro = "ubuntu"
description = "ubuntu LTS 1404 amd64 virtualbox vagrant build w salt installed"
arch = "amd64"
image = "server"
release = "14.04"
builder_types = [
	"virtualbox-iso"
]
	[1404-salt-vagrant.provisioners]
		[1404-salt-vagrant.provisioners.shell.arrays]
		scripts = [
			"setup",
			"sudoers",
			"user_vagrant",
			"salt",
			"vbox",
			"cleanup"
		]
