#!/usr/bin/env bash
UNAME=vagrant
# Set up sudo
echo %$UNAME ALL=NOPASSWD:ALL > /etc/sudoers.d/$UNAME
chmod 0440 /etc/sudoers.d/$UNAME

# Setup sudo to allow no-password sudo for "sudo"
usermod -a -G sudo $UNAME

# Install Vagrant keys
mkdir /home/$UNAME/.ssh
wget --no-check-certificate 'https://raw.githubusercontent.com/mitchellh/vagrant/master/keys/vagrant.pub' -O /home/$UNAME/.ssh/authorized_keys
chown -R $UNAME:$UNAME /home/$UNAME/.ssh
chmod 700 /home/$UNAME/.ssh
chmod 600 /home/$UNAME/.ssh/authorized_keys
