#!/bin/bash
# Install VirtualBox Guest Additions
# necessary:
yum install -y xserver-xorg xserver-xorg-core
cd /tmp
mkdir /mnt/iso
mount -o loop /home/vagrant/VBoxGuestAdditions.iso /mnt/iso
sh /mnt/iso/VBoxLinuxAdditions.run
umount /mnt/iso
rmdir -f /mnt/iso
rm -f /home/vagrant/VBoxGuestAdditions.iso
