#!/bin/bash
# references:
#    http://vstone.eu/reducing-vagrant-box-size/
#    https://github.com/mitchellh/vagrant/issues/343
PATH=$PATH:/sbin:/usr/sbin:/usr/local/sbin
rm -f /home/vagrant/VBoxGuestAdditions*.iso
DEBIAN_FRONTEND=noninteractive apt-get install -fy
DEBIAN_FRONTEND=noninteractive apt-get -y install deborphan
DEBIAN_FRONTEND=noninteractive deborphan | xargs apt-get purge -y
DEBIAN_FRONTEND=noninteractive apt-get clean -y
DEBIAN_FRONTEND=noninteractive apt-get autoclean -y
DEBIAN_FRONTEND=noninteractive apt-get autoremove -y
DEBIAN_FRONTEND=noninteractive apt-get purge -y locate

# delete old dev libraries
DEBIAN_FRONTEND=noninteractive dpkg -l | grep -- '-dev' | xargs apt-get purge -y

# the history isn't needed
DEBIAN_FRONTEND=noninteractive unset HISTFILE
DEBIAN_FRONTEND=noninteractive rm -f /root/.bash_history
DEBIAN_FRONTEND=noninteractive rm -f /home/vagrant/.bash_history

# log files
DEBIAN_FRONTEND=noninteractive find /var/log -type f | while read f; do echo -ne '' > $f; done;

echo 'Whiteout root'
DEBIAN_FRONTEND=noninteractive count=`df --sync -kP / | tail -n1  | awk -F ' ' '{print $4}'`; 
DEBIAN_FRONTEND=noninteractive count=$((count-1))
DEBIAN_FRONTEND=noninteractive dd if=/dev/zero of=/tmp/whitespace bs=1024 count=$count;
DEBIAN_FRONTEND=noninteractive rm /tmp/whitespace;
 
echo 'Whiteout /boot'
DEBIAN_FRONTEND=noninteractive count=`df --sync -kP /boot | tail -n1 | awk -F ' ' '{print $4}'`;
DEBIAN_FRONTEND=noninteractive count=$((count-1))
DEBIAN_FRONTEND=noninteractive dd if=/dev/zero of=/boot/whitespace bs=1024 count=$count;
DEBIAN_FRONTEND=noninteractive rm /boot/whitespace;
 
# zero all empty space
DEBIAN_FRONTEND=noninteractive dd if=/dev/zero of=/EMPTY bs=1M
DEBIAN_FRONTEND=noninteractive rm -f /EMPTY