#!/bin/bash
# references:
#    http://vstone.eu/reducing-vagrant-box-size/
#    https://github.com/mitchellh/vagrant/issues/343

rm -f /home/vagrant/VBoxGuestAdditions*.iso
apt-get -y install deborphan
deborphan | xargs sudo apt-get purge -y
apt-get clean -y
apt-get autoclean -y
apt-get autoremove -y
apt-get purge -y locate

# delete old dev libraries
dpkg -l | grep -- '-dev' | xargs apt-get purge -y

# the history isn't needed
unset HISTFILE
rm -f /root/.bash_history
rm -f /home/vagrant/.bash_history

# log files
find /var/log -type f | while read f; do echo -ne '' > $f; done;

echo 'Whiteout root'
count=`df --sync -kP / | tail -n1  | awk -F ' ' '{print $4}'`; 
count=$((count-1))
dd if=/dev/zero of=/tmp/whitespace bs=1024 count=$count;
rm /tmp/whitespace;
 
echo 'Whiteout /boot'
count=`df --sync -kP /boot | tail -n1 | awk -F ' ' '{print $4}'`;
count=$((count-1))
dd if=/dev/zero of=/boot/whitespace bs=1024 count=$count;
rm /boot/whitespace;
 
# zero all empty space
dd if=/dev/zero of=/EMPTY bs=1M
rm -f /EMPTY