#!/bin/bash
# install some stuff we'll need. Some of this may already be installed but
# that's ok.
PATH=$PATH:/sbin:/usr/sbin:/usr/local/sbin
DEBIAN_FRONTEND=noninteractive apt-get update
DEBIAN_FRONTEND=noninteractive apt-get install -y build-essential libssl-dev libcurl4-gnutls-dev libexpat1-dev gettext

# install git
DEBIAN_FRONTEND=noninteractive apt-get install -y git

# typescript
npm install -g typescript

# lua: 5.2 was latest at time of writing.
DEBIAN_FRONTEND=noninteractive apt-get install -y lua5.2

# rust
wget https://static.rust-lang.org/rustup.sh -O /tmp/rustup.sh
sh /tmp/rustup.sh -y
rm -f /tmp/rustup.sh
