#!/bin/bash
date > /etc/packer_build_time
apt-get update
apt-get upgrade -y
apt-get install -y bzip2 curl git rsync tree wget vim
apt-get install -y liblz4-tool
apt-get -y install build-essential dkms linux-headers-$(uname -r)

