#!/bin/bash

UNAME=vagrant
# Set up the user for sudo
echo %$UNAME ALL=NOPASSWD:ALL > /etc/sudoers.d/$UNAME
echo 'Defaults:vagrant !requiretty' >> /etc/sudoers.d/$UNAME
chmod 0440 /etc/sudoers.d/$UNAME

# Add the user to sudoers
usermod -a -G sudo $UNAME
# Add the user to netdev
usermod -a -G netdev $UNAME

# setup user keys using vagrant's insecure keys
# note: vagrant keys are well known and insecure, which is why we can add them
#       this way. For your private keys, make sure they do not end up in your
#       Git repo, or any other publicly available resource. You should have a
#       secure way of handling private keys.
mkdir -p /home/$UNAME/.ssh
wget --no-check-certificate 'https://raw.githubusercontent.com/mitchellh/vagrant/master/keys/vagrant.pub' -O /home/$UNAME/.ssh/authorized_keys
chown -R $UNAME:$UNAME /home/$UNAME/.ssh
chmod 700 /home/$UNAME/.ssh
chmod 600 /home/$UNAME/.ssh/authorized_keys
